FenixEdu/fenixedu-academic

- src/main/java/org/fenixedu/academic/domain/phd/serviceRequests/documentRequests/PhdDiplomaSupplementRequest.java
- src/main/java/org/fenixedu/academic/domain/serviceRequests/IDiplomaSupplementRequest.java
- src/main/java/org/fenixedu/academic/domain/serviceRequests/documentRequests/DiplomaSupplementRequest.java
- src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/DiplomaSupplement.java
- src/main/resources/resources/AcademicAdminOffice_en.properties
- src/main/resources/resources/AcademicAdminOffice_pt.properties
Changed the diploma supplement related classes to address a series of bugs. This mirrors fenix's 3.14.x branch merges #606, #608 and #609.
> Diploma Supplement Bug Fix

- src/main/webapp/mobility/outbound/OutboundMobilityCandidacy.jsp
Jasper was not generating the correct bundleutil import. Using bundleutil fullpath now
> Fixed mobility access

- src/main/java/org/fenixedu/academic/domain/Degree.java
- src/main/java/org/fenixedu/academic/domain/DegreeCurricularPlan.java
- src/main/java/org/fenixedu/academic/domain/EmptyDegree.java
- src/main/java/org/fenixedu/academic/domain/degreeStructure/RootCourseGroup.java
- src/main/java/org/fenixedu/academic/service/services/scientificCouncil/curricularPlans/CreateDegreeCurricularPlan.java
Closes [ACADEMIC-636](https://jira.fenixedu.org/browse/ACADEMIC-636)
> Bologna independent DCP group structure creation

- src/main/java/org/fenixedu/academic/domain/CompetenceCourse.java
- src/main/java/org/fenixedu/academic/domain/CurricularCourse.java
- src/main/java/org/fenixedu/academic/domain/ExecutionInterval.java
- src/main/java/org/fenixedu/academic/domain/ExecutionSemester.java
- src/main/java/org/fenixedu/academic/domain/ExecutionYear.java
- src/main/java/org/fenixedu/academic/domain/degreeStructure/CompetenceCourseInformation.java
- src/main/java/org/fenixedu/academic/domain/degreeStructure/CycleCourseGroup.java
- src/main/java/org/fenixedu/academic/domain/degreeStructure/CycleCourseGroupInformation.java
- src/main/java/org/fenixedu/academic/domain/degreeStructure/DegreeModule.java
Closes [ACADEMIC-638](https://jira.fenixedu.org/browse/ACADEMIC-638)
> Curricular management API cleanup and enhancement

- src/main/java/org/fenixedu/academic/ui/spring/controller/teacher/authorization/AuthorizationController.java
- src/main/java/org/fenixedu/academic/ui/struts/action/teacher/executionCourse/TeachersManagerDA.java
When a teacher adds another teacher a teacher authorization must exist
within the semester of the execution course.
> Bug Fix: Only add teacher with authorization

- src/main/java/org/fenixedu/academic/json/adapters/AttendsJsonAdapter.java
- src/main/webapp/teacher/executionCourse/attendsSearch/attendsSearchApp.js
- src/main/webapp/teacher/executionCourse/attendsSearch/viewStudentList.jsp
Enrolment count are the total number of enrolments on the course.
> Adds 'all' option to filters on student list

- src/main/java/org/fenixedu/academic/dto/candidacy/PrecedentDegreeInformationBean.java
- src/main/webapp/masterDegreeAdministrativeOffice/candidacy/showCandidacyAlterData.jsp
- added filters to degree designation search
- degree designation wasn't allways being filled in when showing data from database
> Minor change: allowing edition of precedent degree information

- src/main/java/org/fenixedu/academic/ui/spring/controller/student/StudentGroupingService.java
- src/main/webapp/student/groupings/studentGroup.jsp
- src/main/webapp/student/groupings/studentGroupingsApp.js
- Fix: Removes minimum number of elements on individual groupings.
- Fix: Removes persistent error messsages
- Fix: Enables deselection of grouping elements when group has maximum size
- Fix: Corrects behaviour of  clear selection
- Fix: Labels
> Fixes on student group interface

- src/main/java/org/fenixedu/academic/ui/spring/controller/teacher/AttendsSearchController.java
- src/main/webapp/teacher/executionCourse/attendsSearch/attendsSearchApp.js
- src/main/webapp/teacher/executionCourse/attendsSearch/viewStudentList.jsp
- Fix: Changes generated spreadsheets names, so they are different.
- Fix: Adds grouping information in student spreadsheet.
- Fix: Reduces number of digests made by angular, that were forcing a page reload.
> Fixes student list for teachers

- README.md
The title on the repository should also change from:
> (...) is open source (...)
to
> (...) is **an** open source (...)
> Improve English on README.md

- src/main/java/org/fenixedu/academic/domain/accessControl/StudentGroup.java
because it was returning the first regi...stration for degreetype argument and not all, leading to missing some email recipients
> fixed get students by degreeType

- src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/DiplomaSupplement.java
it needs to be consistent in the document
> Corrected the university name legend

- src/main/java/org/fenixedu/academic/domain/alumni/AlumniReportFile.java
The alumni report would never finish, now it gets concluded and becomes available to the user
> ACDM-675 #resolve

- src/main/java/org/fenixedu/academic/ui/spring/controller/teacher/GroupingController.java
- src/main/resources/resources/ApplicationResources_en.properties
- src/main/resources/resources/ApplicationResources_pt.properties
> Prevents negative capacities on groupings. ACDM-676 #resolve

- src/main/java/org/fenixedu/academic/ui/spring/controller/student/StudentGroupingService.java
Fix: student group creation of no shift groups.
> Fixes creating of groups for groupings with no shifts. ACDM-687 #resolve

- src/main/webapp/teacher/executionCourse/groupings/insertGroupProperties.jsp
Fix grouping creation with automatic enrolment
> Fix #ACDM-696

- src/main/java/org/fenixedu/academic/domain/Degree.java
- src/main/java/org/fenixedu/academic/service/services/scientificCouncil/curricularPlans/CreateDegree.java
Relates to #LRN-20
(after the acceptance and release of this request, there will be made a commit in fenixedu-learning that depends on this)
> Signal raising logic for Degree creation.

- src/main/java/org/fenixedu/academic/domain/thesis/ThesisEvaluationParticipant.java
fixed thesis participant comparator not prepared for external participants
> fixed thesis participant comparator 

- src/main/dml/fenixedu-academic.dml
- src/main/java/org/fenixedu/academic/domain/candidacy/workflow/RegistrationOperation.java
- src/main/java/org/fenixedu/academic/domain/student/Registration.java
- src/main/java/org/fenixedu/academic/domain/student/RegistrationDataByExecutionYear.java
- src/main/java/org/fenixedu/academic/domain/studentCurriculum/StudentCurricularPlanEnrolmentManager.java
- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/studentEnrolment/ManageRegistrationDataByExecutionYearDA.java
- src/main/resources/resources/AcademicAdminOffice_en.properties
- src/main/resources/resources/AcademicAdminOffice_pt.properties
- src/main/webapp/academicAdminOffice/student/registration/manageRegistrationDataByExecutionYear/editRegistrationDataByExecutionYear.jsp
- src/main/webapp/academicAdminOffice/student/registration/viewRegistrationDetails.jsp
> Add support to set 'oficial' enrolment date

- src/main/java/org/fenixedu/academic/api/FenixAPIv1.java
- src/main/java/org/fenixedu/academic/api/beans/FenixPayment.java
Add external id to payment events returned by person payments endpoint.
Issue: ACDM-729
> Add external id to person payments endpoint. ACDM-729 #resolve

- src/main/webapp/WEB-INF/fenixedu-academic/schemas/caseHandling-schemas.xml
> Record the names of the candidates that apply to public candidacies

- src/main/dml/fenixedu-academic.dml
- src/main/java/org/fenixedu/academic/domain/TeacherAuthorization.java
- src/main/webapp/WEB-INF/fenixedu-academic/teacher/authorization/revoked.jsp
- src/main/webapp/WEB-INF/fenixedu-academic/teacher/authorization/show.jsp
- src/main/webapp/WEB-INF/resources/ApplicationResources_en.properties
- src/main/webapp/WEB-INF/resources/ApplicationResources_pt.properties
* Slightly improved revoked authorizations view
* Issue: ACDM-657
> Added creation date to Teacher Authorizations

- doc/migration/4.x-5.0.md
The degree's scale is used in the conclusion process
when raw and final grade are editable.
Issue: ACDM-762
> ACDM-762 #comment Add script to set the degree scale of each degree.

- src/main/java/org/fenixedu/academic/domain/serviceRequests/documentRequests/RegistryDiplomaRequest.java
Fixes a bug where the value of the final grade was incorrect.
Issue: ACDM-762
> ACDM-762 #comment Return the right value for final grade

- src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/DegreeFinalizationCertificate.java
- src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/Diploma.java
- src/main/resources/resources/AcademicAdminOffice_en.properties
- src/main/resources/resources/AcademicAdminOffice_pt.properties
* The article before program conclusion in diploma must be genre agnostic.
* Use program conclusion description instead of degreeType name.
Issue: ACDM-690
> ACDM-690 #comment Fix program conclusion description usage

- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/student/RegistrationDA.java
> ACDM-690 #comment Program conclusion selection is mandatory

- src/main/java/org/fenixedu/academic/domain/thesis/ThesisEvaluationParticipant.java
- src/main/java/org/fenixedu/academic/service/services/scientificCouncil/thesis/ApproveThesisDiscussion.java
- src/main/java/org/fenixedu/academic/service/services/scientificCouncil/thesis/ApproveThesisProposal.java
- src/main/java/org/fenixedu/academic/service/services/scientificCouncil/thesis/ThesisServiceWithMailNotification.java
when there is an external participant  it may not have an associated person
> Corrected problem in the thesis email notification ACDM-782 #resolve

- src/main/webapp/WEB-INF/fenixedu-academic/schemas/academicAdminOffice-schemas.xml
Smal fix to already closed issue (not released) ACADEMIC-648.
> [Statutes] Fix: Corrected a small presentation problem with the LocalizedString

- src/main/java/org/fenixedu/academic/domain/studentCurriculum/Credits.java
- src/main/java/org/fenixedu/academic/domain/studentCurriculum/Equivalence.java
- src/main/java/org/fenixedu/academic/domain/studentCurriculum/InternalSubstitution.java
- src/main/java/org/fenixedu/academic/domain/studentCurriculum/Substitution.java
- src/main/java/org/fenixedu/academic/domain/studentCurriculum/TemporarySubstitution.java
- src/main/webapp/WEB-INF/fenixedu-academic/schemas/academicAdminOffice-schemas.xml
- src/main/webapp/academicAdminOffice/dismissal/managementDismissals.jsp
> [Dismissals] Added a descriptive dismissal type that is shown in the student dismissals management interface

- src/main/java/org/fenixedu/academic/domain/candidacyProcess/IndividualCandidacyExternalPersonDetails.java
if the person doesn't exist it has to be created, but before checking if already exists
> Creating a registration from a candidacy is now possible ACDM-662 #resolve

- src/main/webapp/WEB-INF/fenixedu-academic/schemas/academicAdminOffice-schemas.xml
Small fix to already closed issue (not released) ACADEMIC-647.
> [Ingressions] Fix: Corrected a small presentation problem with the LocalizedString description

- src/main/java/org/fenixedu/academic/domain/ExecutionCourse.java
- src/main/java/org/fenixedu/academic/ui/struts/action/resourceAllocationManager/ManageLessonDA.java
> Fix NPE when attempting to create a Lesson without LessonPeriod defined

- src/main/java/org/fenixedu/academic/ui/faces/bean/academicAdministration/curricularPlans/AcademicAdministrationCurricularCourseManagementBackingBean.java
> Remove execution year filter by execution degree on advanced curricular management UI

- src/main/java/org/fenixedu/academic/domain/thesis/ThesisEvaluationParticipant.java
Now accepting external advisors
> Fix comparator for ThesisEvaluationParticipant ACDM-802 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/coordinator/DegreeSiteManagementDispatchAction.java
Fixes error from locale misuse
> Fix edit degree curricular plan description on coordinador ACDM-771 #resolve

- src/main/java/org/fenixedu/academic/domain/phd/serviceRequests/documentRequests/PhdDiplomaRequest.java
- src/main/java/org/fenixedu/academic/domain/phd/serviceRequests/documentRequests/PhdDiplomaSupplementRequest.java
- src/main/java/org/fenixedu/academic/domain/phd/serviceRequests/documentRequests/PhdRegistryDiplomaRequest.java
- src/main/java/org/fenixedu/academic/domain/phd/thesis/activities/ConcludePhdProcess.java
- src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/AdministrativeOfficeDocument.java
- src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/DiplomaSupplement.java
- src/main/resources/resources/ApplicationResources_en.properties
- src/main/resources/resources/ApplicationResources_pt.properties
* use registration from phd individual process when request is for phd
* get degree from registration instead of specific request implementation
* get program conclusion for phd requests (used to get the graduation level)
Issue: ACDM-804
> Fix PhD document requests for program conclusion. ACDM-804 #resolve

- src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/EnrolmentCertificate.java
- src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/EnrolmentDeclaration.java
Enrolment certificate and declaration now uses the correct api to get
the degree description using the requested document language.
Issue: ACDM-805
> Degree description depends on requested language. ACDM-805 #resolve

- src/main/java/org/fenixedu/academic/domain/util/Email.java
> Fix Email Date Header format. ACDM-800 #resolve

- src/main/java/org/fenixedu/academic/ui/faces/bean/sop/evaluation/SOPEvaluationManagementBackingBean.java
> Fixed presentation of Degree Types in Evaluation Schedules interface

- src/main/java/org/fenixedu/academic/domain/DegreeCurricularPlan.java
> Fix degree curricular plan creation. ACDM-807 #resolve

- src/main/java/org/fenixedu/academic/domain/util/Email.java
> Localize Date Header on email messages. ACDM-816 #resolve

- src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/RegistryDiploma.java
Translate label of both to the requested document language.
Issue: ACDM-813
> Translate label of both in Registry Diploma. ACDM-813 #resolve

- src/main/java/org/fenixedu/academic/domain/phd/serviceRequests/documentRequests/PhdDiplomaSupplementRequest.java
- src/main/java/org/fenixedu/academic/domain/phd/thesis/activities/ConcludePhdProcess.java
- src/main/java/org/fenixedu/academic/domain/student/Registration.java
- src/main/java/org/fenixedu/academic/ui/struts/action/phd/thesis/academicAdminOffice/PhdThesisProcessDA.java
The conclusion date should be obtain from the third cycle group
directly until the phd refactor is done.
Issue:ACDM-814
> Fix conclusion date for phd documents. ACDM-814 #resolve

- src/main/java/org/fenixedu/academic/domain/student/Registration.java
> Ignore program conclusion name when terminal ACDM-819 #resolve

- src/main/webapp/candidacy/erasmus/assignCoordinator.jsp
- src/main/webapp/coordinator/degreeCurricularPlan/showEquivalencyPlan.jsp
- src/main/webapp/externalSupervision/consult/selectDegree.jsp
- src/main/webapp/gep/ects/comparabilityTableIndex.jsp
- src/main/webapp/manager/degreeCurricularPlan/showEquivalencyPlan.jsp
DegreeType was changed and the method getLocalizedName was removed as
name is now a localizedString. The JSPs that relied on this property
were updated to reflect this change.
> Updated JSPs to point to the right Property #Resolves ACDM-821

- src/main/java/org/fenixedu/academic/ui/renderers/providers/BolonhaDegreeTypesProvider.java
> Bug Fix: BolonhaDegreeTypesProvider no longer defines an EnumConverter

- src/main/java/org/fenixedu/academic/ui/struts/action/resourceAllocationManager/exams/WrittenEvaluationsSearchByDegreeAndYear.java
> Use proper degree name when searching for evaluations by degree

- src/main/webapp/resourceAllocationManager/periods/managePeriods.jsp
- src/main/webapp/resourceAllocationManager/periods/managePeriodsScripts.jsp
> Adjusted CSS breakpoints in Periods Management interface

- src/main/java/org/fenixedu/academic/dto/resourceAllocationManager/PeriodsManagementBean.java
- src/main/webapp/resourceAllocationManager/periods/managePeriods.jsp
* These are limited according to the configured EvaluationSeasons
* Issue: ACDM-863
> Limit the available period types in the Period Management interface

- src/main/java/org/fenixedu/academic/domain/curricularRules/AnyCurricularCourse.java
> Bug fix: Unable to delete AnyCurricularCourse rule when associated with a degree type

- src/main/java/org/fenixedu/academic/domain/CurricularCourse.java
> CurricularCourse no longer assumes default values for Credits and Weight

- src/main/webapp/academicAdministration/bolonha/curricularPlans/curricularPlansManagement.jsp
- src/main/webapp/academicAdministration/bolonha/curricularPlans/viewCurricularPlan.jsp
> Academic office curricular management UI should allow curricularplans visualization for users without management permissions

- src/main/java/org/fenixedu/academic/domain/IEnrolment.java
- src/main/java/org/fenixedu/academic/dto/student/ExecutionPeriodStatisticsBean.java
- src/main/java/org/fenixedu/academic/ui/renderers/student/curriculum/StudentCurricularPlanRenderer.java
> Code should not assume that final grades are integers

- src/main/webapp/academicAdminOffice/student/enrollment/bolonha/showDegreeModulesToEnrol.jsp
> Inconsistency between Student's and AdminOffice's enrollment screen.

- src/main/java/org/fenixedu/academic/domain/contacts/EmailValidation.java
> Remove ist hard-coded references from e-mail validation

- src/main/dml/fenixedu-academic.dml
- src/main/java/org/fenixedu/academic/domain/Installation.java
- src/main/webapp/publico/alumni/alumniPublicAccess.jsp
- src/main/webapp/student/enrollment/bolonha/showDegreeModulesToEnrol.jsp
> Minor fix: removing hardcoded "academica@tecnico.pt". Added new domain configuration to replace these cases

- src/main/java/org/fenixedu/academic/domain/student/Student.java
> Allow generation of student numbers above 100000. ACDM-893 #resolve

- src/main/java/org/fenixedu/academic/domain/student/SeniorStatute.java
> Allow deleting Senior Statutes

- src/main/webapp/WEB-INF/fenixedu-academic/schemas/academicAdminOffice-schemas.xml
> Academic Admin Office UI now allows degree type selection

- src/main/java/org/fenixedu/academic/domain/ExecutionCourse.java
- src/main/java/org/fenixedu/academic/domain/Shift.java
- src/main/webapp/resourceAllocationManager/manageShift_bd.jsp
> Enable Shift name edition (without extra slot)

- src/main/java/org/fenixedu/academic/ui/spring/controller/PhotographController.java
> PhotographController now only allows sizes between 1 and 512

- src/main/java/org/fenixedu/academic/domain/candidacy/workflow/FillPersonalDataOperation.java
- src/main/java/org/fenixedu/academic/domain/candidacy/workflow/form/ContactsForm.java
- src/main/resources/resources/CandidateResources_en.properties
- src/main/resources/resources/CandidateResources_pt.properties
- src/main/webapp/WEB-INF/fenixedu-academic/schemas/candidacy-schemas.xml
> Emergency Contact is now requested during 1st time student registration

- src/main/java/org/fenixedu/academic/domain/curricularRules/MaximumNumberOfEctsInStandaloneCurriculumGroup.java
Update MAXIMUM_DEFAULT_VALUE for standalone curricular group due to rule changes.
ACDM-933 #resolve
> Update MAXIMUM_DEFAULT_VALUE to 30. ACDM-933 #resolve #933

- src/main/webapp/WEB-INF/fenixedu-academic/schemas/resourceAllocationManager-schemas.xml
> added an empty option to enable degree selection, even if there is only one degree available

- src/main/webapp/academicAdminOffice/student/enrollment/bolonha/chooseOptionalCurricularCourseToEnrol.jsp
- src/main/webapp/student/enrollment/bolonha/chooseOptionalCurricularCourseToEnrol.jsp
> Styling inconsistency on the optional courses enrollment screens.

- src/main/java/org/fenixedu/academic/ui/renderers/providers/executionDegree/DegreesToCreateRegistration.java
> Bug fix: Correctly sort degrees on registration creation

- src/main/java/org/fenixedu/academic/ui/struts/action/teacher/executionCourse/EvaluationMethodDA.java
- src/main/webapp/teacher/executionCourse/evaluationMethod.jsp
> Fixed UI for evaluation method edit, was not showing edited values properly

- src/main/java/org/fenixedu/academic/ui/struts/action/academicAdministration/ManageEnrolementPeriodsDA.java
- src/main/webapp/academicAdministration/enrolmentPeriodManagement/createPeriod.jsp
> It is now possible to define enrolment periods for Standalone Degrees

- src/main/java/org/fenixedu/academic/ui/renderers/student/curriculum/StudentCurricularPlanRenderer.java
> Enable customization of student curricular plan renderer. ACDM-894 #resolve

- src/main/java/org/fenixedu/academic/ui/spring/controller/PhotographController.java
> Minor Fix: Allow support for usernames with dots, in PhotographController

- src/main/java/org/fenixedu/academic/domain/studentCurriculum/StudentCurricularPlanExtraEnrolmentManager.java
- src/main/java/org/fenixedu/academic/domain/studentCurriculum/StudentCurricularPlanPropaeudeuticsEnrolmentManager.java
- src/main/java/org/fenixedu/academic/domain/studentCurriculum/StudentCurricularPlanStandaloneEnrolmentManager.java
> Update Enrolment Date when Enrolment is performed by the services

- src/main/webapp/student/enrollment/bolonha/showDegreeModulesToEnrol.jsp
> Avoid error in student enrolment when degree does not have a configured siteURL

- src/main/webapp/student/enrollment/bolonha/showDegreeModulesToEnrol.jsp
> Added warning messages to student enrolment page

- src/main/java/org/fenixedu/academic/domain/Degree.java
> Fix: Corrected NPE when trying to obtain the most recent DegreeCurricularPlan of a Degree

- src/main/java/org/fenixedu/academic/domain/ExecutionDegree.java
> executionDegree delete fix: disconnect PublishedExamMaps relation

- src/main/java/org/fenixedu/academic/domain/student/Registration.java
- src/main/java/org/fenixedu/academic/domain/studentCurriculum/StudentCurricularPlanEnrolmentInSpecialSeasonEvaluationManager.java
> Removed restriction of online enrolments to specific degree types

- src/main/java/org/fenixedu/academic/ui/renderers/student/enrollment/bolonha/BolonhaStudentEnrolmentLayout.java
> [JIRA] (ACDM-939) Enrolments UI: streamline behaviour of enroled and not enroled CurriculumModules

- src/main/java/org/fenixedu/academic/domain/studentCurriculum/StudentCurricularPlanEnrolment.java
> [JIRA] (ACDM-969) Improvement: Possibility to plug new enrolment managers

- src/main/webapp/WEB-INF/fenixedu-academic/schemas/executionCourse-schemas.xml
> In summaries management, the shift name should be visible

- src/main/java/org/fenixedu/academic/ui/struts/action/coordinator/candidacy/graduatedPerson/DegreeCandidacyForGraduatedPersonProcessDA.java
- src/main/webapp/coordinator/candidacy/graduatedPerson/mainCandidacyProcess.jsp
> Added support more multiple periods in coordinator portal ACDM-962 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/academicAdministration/ManageEnrolementPeriodsDA.java
- showing curricular plans in the period management interface that have transitioned in the year before
> Allow improvement enrolment period for transitioned curricular plans ACDM-952 #resolve

- src/main/java/org/fenixedu/academic/domain/util/Email.java
> [JIRA] (ACDM-981) Email: fix Message-ID header format

- src/main/java/org/fenixedu/academic/domain/phd/PhdProcessState.java
- src/main/java/org/fenixedu/academic/ui/struts/action/phd/academicAdminOffice/PhdAccountingEventsManagementDA.java
- fixed the state comparator, the state date is the one to be compared not the creation date
> Corrected the way the states are checked to generate Phd gratuity debt ACDM-987 #resolve

- src/main/resources/resources/EnumerationResources_en.properties
- src/main/resources/resources/EnumerationResources_pt.properties
- src/main/webapp/phd/coordinator/publicProgram/viewProcess.jsp
- also added missing EPFL label
> Corrected the hashcode injection on phd coordinator view process ACDM-1012 #resolve

- src/main/java/org/fenixedu/academic/ui/spring/controller/academicAdministration/MoveRegistrationsController.java
in one of the two merging parties
> ACDM-994 #resolve Remove requirement of ss number

- src/main/java/org/fenixedu/academic/ui/renderers/providers/ExecutionDegreeForExecutionPeriodAcademicAdminProvider.java
it's now possible to see all execution degrees for same degree and year, not only one
> Allowing UI to deal with more than one execution degree ACDM-1024 #resolve

- src/main/java/org/fenixedu/academic/service/services/commons/alumni/AlumniNotificationService.java
- src/main/resources/resources/ManagerResources_en.properties
- src/main/resources/resources/ManagerResources_pt.properties
As an alternative solution started relying on cas.serverUrl property.
> Removed hardcoded IST cas server url. ACDM-1033 #resolve

- src/main/java/org/fenixedu/academic/domain/phd/SearchPhdIndividualProgramProcessBean.java
> Improvement: Made PHD Process search by name smarter

- src/main/java/org/fenixedu/academic/domain/accessControl/AllAlumniGroup.java
> Fixed allAlumniGroup to include alumni without registration.

- src/main/java/org/fenixedu/academic/domain/CompetenceCourse.java
The way of getting a Competence Course name is now uniform for all
> Removed different behaviour retrieving Competence name ACDM-1045 #resolve

- src/main/resources/resources/ApplicationResources_en.properties
- src/main/resources/resources/ApplicationResources_pt.properties
- src/main/webapp/WEB-INF/fenixedu-academic/schemas/student-schemas.xml
> Complement student search results with the name of the degrees for which the students have active registrations

- src/main/webapp/WEB-INF/fenixedu-academic/schemas/academicAdminOffice-schemas.xml
> [StudentStatutes] Minor: Allowed viewing the begin and end dates of student statutes.

- src/main/java/org/fenixedu/academic/domain/util/email/Sender.java
> Fixed sender delete to unlink access group

- src/main/java/org/fenixedu/academic/domain/ExecutionCourse.java
- src/main/java/org/fenixedu/academic/domain/util/email/ExecutionCourseSender.java
- src/main/java/org/fenixedu/academic/service/services/manager/MergeExecutionCourses.java
> Ensure ExecutionCourseSenders will not have null execution courses

- src/main/java/org/fenixedu/academic/domain/Person.java
- src/main/java/org/fenixedu/academic/domain/contacts/EmailAddress.java
- src/main/java/org/fenixedu/academic/ui/struts/action/accounts/SearchParametersBean.java
Filter inactive & invalid email addresses, return all matches
> Manage Account Email Search. ACDM-1046 #resolve

- src/main/webapp/WEB-INF/fenixedu-academic/schemas/phd-program-schemas.xml
- src/main/webapp/phd/academicAdminOffice/manageGuidingInformation.jsp
Add acceptance letter link to PhdProgramGuiding.view
Use PhdProgramGuiding.view schema in orientator detailed view at manageguidinginformation.jsp
> Add acceptance letter link to PhdProgramGuiding.view  ACDM-1074 #resolve

- src/main/webapp/student/curriculum/viewRegistrationCurriculum.jsp
Present RegistrationCurriculumBean's execution year's curriculum ECTS and grade in student curriculum view
> Present correct Curriculum ECTS in student curriculum view ACDM-1075 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/serviceRequests/RectorateDocumentSubmissionDispatchAction.java
Fix diploma supplement from being added to rectorate batch when a user delays an academic rquest. ACDM-1072 #resolve
> Diploma supplement no longer added to rectorate batch.

- src/main/java/org/fenixedu/academic/domain/phd/reports/PhdIndividualProgramProcessesReport.java
- src/main/resources/resources/PhdResources_en.properties
- src/main/resources/resources/PhdResources_pt.properties
Exported excel in Phd Process now includes email column
ACDM-1056 #resolve
> add email column in academic student report. ACDM-1056 #resolve

- src/main/java/org/fenixedu/academic/predicate/MarkSheetPredicates.java
- src/main/java/org/fenixedu/academic/service/services/administrativeOffice/gradeSubmission/CreateMarkSheetByTeacher.java
Remove overly strict active teacher check in CreateMarkSheetByTeacher
Replace same strict check in edit marksheet predicate with a check for a professorship on one of the marksheet's execution courses
> Allow teachers to submit grades for their courses after semester change ACDM-896 ACDM-1041 #resolve

- src/main/java/org/fenixedu/academic/dto/student/StudentPortalBean.java
- src/main/java/org/fenixedu/academic/service/factory/RoomSiteComponentBuilder.java
- src/main/java/org/fenixedu/academic/ui/faces/bean/student/enrolment/DisplayEvaluationsForStudentToEnrol.java
- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/serviceRequests/documentRequests/DocumentRequestsManagementDispatchAction.java
The following PR resolves part of the issue:
https://github.com/ist-dsi/fenixedu-ist/pull/197
> showing exams information should always check for the exam map state ACDM-658 #resolve

- src/main/dml/fenixedu-academic.dml
- src/main/java/org/fenixedu/academic/domain/util/email/ExecutionCourseSender.java
Force ExecutionCourseSender's link to an ExecutionCourse
Fix potential NPE on ExecutionCourseSender comparator by ExecutionCourse
> Force ExecutionCourseSender's link to an ExecutionCourse ACDM-1083 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/accounts/SearchParametersBean.java
Many profiles do not have a linked user until activated
> Search for accounts should not assume a user. ACDM-1111 #resolve

- src/main/java/org/fenixedu/academic/domain/CompetenceCourse.java
- src/main/java/org/fenixedu/academic/domain/CurricularCourse.java
- src/main/java/org/fenixedu/academic/domain/DegreeCurricularPlan.java
- src/main/java/org/fenixedu/academic/domain/degreeStructure/OptionalCurricularCourse.java
- src/main/java/org/fenixedu/academic/service/services/bolonhaManager/EditCurricularCourse.java
- src/main/java/org/fenixedu/academic/ui/faces/bean/academicAdministration/curricularPlans/AcademicAdministrationCurricularCourseManagementBackingBean.java
Remove bolonha degree checks from curricular course information getters
Remove chain of course information attributes in getters delegating all responsibility to CompetenceCourseInformation
Deprecate methods that use these attributes
> Correct Competence Course Information getters ACDM-1142 #resolve

- src/main/dml/fenixedu-academic.dml
- src/main/java/org/fenixedu/academic/domain/accounting/events/gratuity/ExternalScholarshipGratuityExemption.java
- src/main/java/org/fenixedu/academic/domain/accounting/events/gratuity/GratuityContributionFile.java
- src/main/java/org/fenixedu/academic/domain/accounting/events/gratuity/GratuityEvent.java
- src/main/java/org/fenixedu/academic/domain/phd/debts/PhdEventExemptionJustificationType.java
- src/main/java/org/fenixedu/academic/domain/phd/debts/PhdGratuityEvent.java
- src/main/java/org/fenixedu/academic/domain/phd/debts/PhdGratuityExternalScholarshipExemption.java
- src/main/java/org/fenixedu/academic/domain/phd/debts/PhdGratuityPR.java
- src/main/java/org/fenixedu/academic/ui/struts/action/academicAdministration/payments/PaymentsManagementDA.java
- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/payments/PaymentsManagementDispatchAction.java
- src/main/webapp/academicAdminOffice/payments/showExternalEvents.jsp
- src/main/webapp/manager/payments/postingRules/management/prepareAddFCTPostingRule.jsp
- src/main/webapp/manager/payments/postingRules/management/prepareEditFCTScolarshipPostingRule.jsp
Enable transfer of PhD gratuity debts to third parties using the same process as other gratuity debts
> Enable transfer of PhD gratuity debts to third parties

- src/main/java/org/fenixedu/academic/domain/phd/reports/PhdIndividualProgramProcessesReport.java
- src/main/java/org/fenixedu/academic/domain/phd/reports/PhdReport.java
- src/main/resources/resources/PhdResources_en.properties
- src/main/resources/resources/PhdResources_pt.properties
The new columns are as follows : 
Thesis process state
CAT process state
Study plan state
Candidacy process
Also deleted the "Big Spots" cell style, as it was making the header unreadable.
> PHD report now has 4 new columns. ACDM-1097 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/coordinator/thesis/ManageThesisDA.java
- src/main/webapp/coordinator/thesis/editThesis.jsp
Also deleted unused "thesis" variable from ManageThesisDA.java
> Thesis president can now be updated ACDM-1171 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/lists/StudentListByDegreeDA.java
Fix: NPE on getAlmaMater methods when candidacy is null; renamed associated variables.
> Fixed: NPE on getAlmaMater methods ACDM-1149 #resolve

- src/main/java/org/fenixedu/academic/domain/phd/debts/PhdGratuityExternalScholarshipExemption.java
- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/payments/ExemptionsManagementDispatchAction.java
- src/main/java/org/fenixedu/academic/ui/struts/action/phd/PhdEventExemptionBean.java
- src/main/resources/resources/EnumerationResources_en.properties
- src/main/resources/resources/EnumerationResources_pt.properties
- src/main/webapp/phd/academicAdminOffice/payments/exemptions/createPhdEventExemption.jsp
- src/main/webapp/phd/academicAdminOffice/payments/exemptions/showPhdGratuity.jsp
Fix NullPointerException on PhdGratuityExternalScholarshipExemption deletion
Replace party drop down menu in phd exemption creation with an autocomplete input
Add the functionality of creating a debt transfer exemption to the exemptions page
> Fix Debt Transfer Bugs ACDM-1191 #resolve

- src/main/java/org/fenixedu/academic/domain/accounting/events/gratuity/StandaloneEnrolmentGratuityEvent.java
- src/main/java/org/fenixedu/academic/domain/accounting/postingRules/gratuity/StandaloneEnrolmentGratuityPR.java
Fix debt amount calculus to include external entity contibution exemptions
> Fix standalone enrollment gratuity debt amount calculus ACDM-1200 #resolve

- src/main/java/org/fenixedu/academic/domain/accounting/installments/PartialRegimeInstallment.java
- src/main/java/org/fenixedu/academic/dto/accounting/paymentPlan/InstallmentBean.java
Allow semesters to be removed from PartialInstallments and not just added. Also reduce the number of collections that are created for no reason; this also makes the code a bit nicer.
> Allow semesters to be removed from PartialInstallments. ACDM-1205 #resolve

- src/main/java/org/fenixedu/academic/ui/renderers/DegreeCurricularPlanOptionalEnrolmentsRenderer.java
Fixed selection of curricular course when there are multiple occurencss on the same page.
> Fixed selection of multiple curricular course for extra curricular enrolments. ACDM-1206 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/manager/payments/SIBSPaymentsDA.java
Using the correct payment code in report generation
> Fix generation of SIBS report ACDM-1252 #resolve

- src/main/java/org/fenixedu/academic/domain/accounting/PostingRule.java
- src/main/java/org/fenixedu/academic/domain/accounting/report/events/EventReportQueueJob.java
Add original debt value and total exempt amount to debt report
> Add original debt value and total exempt. ACDM-1269 #resolve

- src/main/java/org/fenixedu/academic/domain/contacts/EmailAddress.java
Override PartyContact's deletion process in EmailAddress to also update current profile email
> Update UserProfile email on EmailAddress deletion ACDM-1301 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/HomeAction.java
Avoid multiple request/response pairs to redirect user to the first available interface.
> Avoid Home Action Redirect ACDM-1332 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/manager/payments/PhdPostingRulesManagementDA.java
- src/main/webapp/manager/payments/postingRules/management/phd/showPhdProgramPostingRules.jsp
deleteDegreeCurricularPlanPostingRule in PostingRulesManagementDA.java was redirecting to the wrong jsp.
> Avoid NPE after deleting phd posting rule. ACDM-1319 #request

- src/main/webapp/teacher/executionCourse/groupings/viewStudentGroupInformation.jsp
Add button for the no shift and no students enrolled state
> Restore button to previous location ACDM-1341 #resolve

- src/main/webapp/academicAdminOffice/pricesManagement/viewPrices.jsp
Changed div dimensions from 350x230 to 485x350.
Changed Edit button position to relative to the containing div.
> Fix visual bug that was hiding Edit button in Academic Admnistration ACDM-1322 #resolve

- src/main/java/org/fenixedu/academic/service/services/enrollment/shift/WriteStudentAttendingCourse.java
- src/main/resources/resources/StudentResources_en.properties
- src/main/resources/resources/StudentResources_pt.properties
WriteAttendingCourse.run now throws an exception when the execution course is connected to other registration (the student is already enrolled in the course through other registration).
> WriteStudentAttendingCourse throws an exception on duplicate ExecutionCourse ACDM-1349 #resolve

- src/main/java/org/fenixedu/academic/domain/EnrolmentEvaluation.java
- src/main/resources/resources/AcademicAdminOffice_en.properties
- src/main/resources/resources/AcademicAdminOffice_pt.properties
Changed message to describe the cause of the error properly to the user.
> It should not be possible to create marksheets with annulled enrollment evaluations ACDM-1345 #resolve

- src/main/java/org/fenixedu/academic/domain/phd/email/PhdEmail.java
- src/main/java/org/fenixedu/academic/domain/phd/email/PhdIndividualProgramProcessEmail.java
- src/main/java/org/fenixedu/academic/domain/phd/email/PhdProgramEmail.java
- src/main/java/org/fenixedu/academic/service/GOPSendMessageService.java
- src/main/java/org/fenixedu/academic/service/services/commons/alumni/AlumniNotificationService.java
- src/main/java/org/fenixedu/academic/service/services/scientificCouncil/thesis/ThesisServiceWithMailNotification.java
- src/main/java/org/fenixedu/academic/ui/struts/action/publicRelationsOffice/AlumniCerimonyDA.java
- Fixed some redundant qualified name imports
- (AlumniNotificationService.java) Redundant passing of null parameter
> Review usages of singleBcc from messaging module ACDM-1409 #resolve

- src/main/java/org/fenixedu/academic/domain/accounting/calculator/CreditEntry.java
- src/main/java/org/fenixedu/academic/domain/accounting/calculator/Debt.java
- src/main/java/org/fenixedu/academic/domain/accounting/calculator/DebtInterestCalculator.java
- src/main/java/org/fenixedu/academic/domain/accounting/calculator/Fine.java
- src/main/java/org/fenixedu/academic/ui/spring/controller/AccountingController.java
- src/main/java/org/fenixedu/academic/ui/spring/service/AccountingManagementService.java
- src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-debt-details.jsp
- src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-details.jsp
- src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-payment-details.jsp
Also added "hh:mm:ss" to time information displayed.
> Missing Fines paid details in interface ACDM-1439 #resolve

- src/main/java/org/fenixedu/academic/domain/accounting/PostingRule.java
- src/main/java/org/fenixedu/academic/dto/accounting/EntryDTO.java
- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/payments/PaymentsManagementDispatchAction.java
- src/main/resources/resources/AcademicAdminOffice_en.properties
- src/main/resources/resources/AcademicAdminOffice_pt.properties
Accounting operator must select all penalties entries before
settling debt entries.
Issue: ACDM-1442
> Block payment if penalties are not settled ACDM-1442 #resolve

- src/main/webapp/WEB-INF/manager/interestRates/create.jsp
- src/main/webapp/WEB-INF/resources/ApplicationResources_en.properties
- src/main/webapp/WEB-INF/resources/ApplicationResources_pt.properties
Added interest rate creation/edition warning message
Added confirmation check in interest rate warning message
Made font size of interest rate warning larger
> Added warning message to interest management interface ACDM-1450 #resolve

- src/main/java/org/fenixedu/academic/ui/spring/controller/AccountingController.java
- src/main/java/org/fenixedu/academic/ui/spring/controller/AccountingEventForOwnerController.java
- src/main/java/org/fenixedu/academic/ui/spring/controller/AccountingEventsPaymentManagerController.java
- src/main/java/org/fenixedu/academic/ui/spring/service/AccountingManagementService.java
- src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-create-exemption.jsp
- src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-debt-details.jsp
- src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-deposit.jsp
- src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-exemption-details.jsp
- src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-payment-details.jsp
- src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-payment-options.jsp
- Extended PaymentSummary with typeDescription to be consistent with main interface ("cards")
- Minor url fixes in JSPs
> Fix debt numbering and input money patterns in accounting interfaces ACDM-1465 #resolve

- src/main/dml/fenixedu-academic.dml
- src/main/java/org/fenixedu/academic/domain/accounting/Event.java
Slot for storing original value of event to allow checking for value changes ACDM-1499 #resolve
> Add original value of event slot ACDM-1499 #resolve

- src/main/java/org/fenixedu/academic/domain/accounting/events/AnnualEvent.java
- src/main/java/org/fenixedu/academic/domain/accounting/events/gratuity/GratuityEvent.java
- src/main/java/org/fenixedu/academic/domain/accounting/events/gratuity/PartialRegimeEvent.java
Avoid NullPointerException durring event construction Also display original cause of exceptions  ACDM-1500 #resolve
> Avoid NullPointerException durring event construction ACDM-1500 #resolve

- src/main/java/org/fenixedu/academic/domain/accounting/postingRules/ResidencePR.java
> Fix ResidencePR penalty per day calculations ACDM-1509 #resolve

- src/main/java/org/fenixedu/academic/domain/accessControl/StudentGroup.java
getPresentationName() returns now a description for the arguments.
> Improve student group name ACDM-1529 #resolve

- src/main/webapp/WEB-INF/fenixedu-academic/accounting/events-multiple-payments-confirm.jsp
- src/main/webapp/WEB-INF/resources/ApplicationResources.properties
- src/main/webapp/WEB-INF/resources/ApplicationResources_en.properties
- src/main/webapp/WEB-INF/resources/ApplicationResources_pt.properties
* Improve payment details (bigger font, better detail)
> Confirm when leaving page ACDM-1547 #resolve

- src/main/java/org/fenixedu/academic/report/thesis/StudentThesisIdentificationDocument.java
- src/main/webapp/WEB-INF/fenixedu-academic/schemas/student-schemas.xml
- src/main/webapp/student/thesis/declaration.jsp
- src/main/webapp/student/thesis/submit.jsp
- src/main/webapp/student/thesis/uploadDissertation.jsp
- src/main/webapp/student/thesis/viewDeclaration.jsp
**Change log:**
- Removed parameters that were passing the language to the student thesis identification document;
- Removed language field on "Dissertation Submission" -> "Details";
- Removed language field on "Submit Dissertation";
- Fixed problems with the institution name LocalizedString output on "Dissertation Submission" -> "Declaration".
> Remove language field from student identification thesis report ACDM-1015 #resolve

- src/main/java/org/fenixedu/academic/domain/organizationalStructure/UnitName.java
Note that this provider stopped using the previously implemented indexing strategy.
> Improve RAIDES Academic Unit auto complete provider ACDM-1350 #resolve

- src/main/webapp/publico/candidacy/over23/main.jsp
- src/main/webapp/publico/candidacy/over23/main_en.jsp
- src/main/webapp/publico/candidacy/secondCycle/main.jsp
- src/main/webapp/publico/candidacy/secondCycle/main_en.jsp
Even though the issue only refers to the second cycle context, a quick search revealed the same problem in the over23 context.
> Fix candidacy access recovery link (2nd cycle and over23) ACDM-1313 #resolve

- src/main/java/org/fenixedu/academic/domain/candidacy/GenericApplication.java
- src/main/java/org/fenixedu/academic/domain/period/GenericApplicationPeriod.java
- src/main/java/org/fenixedu/academic/ui/struts/action/publico/candidacies/GenericCandidaciesDA.java
- src/main/resources/resources/CandidateResources_en.properties
- src/main/resources/resources/CandidateResources_pt.properties
- src/main/webapp/publico/candidacy/genericApplications/confirmEmail.jsp
- src/main/webapp/publico/candidacy/genericApplications/listApplicationPeriods.jsp
- src/main/webapp/publico/candidacy/genericApplications/viewApplicationPeriod.jsp
**Changes Done**
~~1. Filter candidacy periods that have already ended and sort by start date.~~
1. Sorted list of candidacy periods by start date.
2. Converted email from properties file to MessageTemplate that can be further customized in runtime.
3. Fix some missing "getContent" in JSPs.
> Improve generic applications user experience ACDM-733 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/mobility/outbound/OutboundMobilityCandidacyDA.java
- src/main/webapp/mobility/outbound/OutboundMobilityCandidacy.jsp
Note: the edits are only submitted successfully when the Option text box has any input.
> Make introductory text be editable in text box ACDM-1628 #resolve

- src/main/java/org/fenixedu/academic/domain/candidacyProcess/IndividualCandidacyExternalPersonDetails.java
the mobile is now requested instead of the phone
> Reading mobile instead of phone ACDM-1667 #resolve

- src/main/java/org/fenixedu/academic/domain/ExecutionDegree.java
- src/main/java/org/fenixedu/academic/domain/Shift.java
- src/main/java/org/fenixedu/academic/domain/candidacy/degree/ShiftDistribution.java
- src/main/java/org/fenixedu/academic/domain/candidacy/workflow/RegistrationOperation.java
- src/main/java/org/fenixedu/academic/ui/struts/action/resourceAllocationManager/ShiftDistributionFileBean.java
> Restrict Student Shift Distribution According to Student Numbers ACDM-1802 #resolve

- src/main/java/org/fenixedu/academic/ui/faces/bean/bolonhaManager/competenceCourses/CompetenceCourseManagementBackingBean.java
> java.lang.NullPointerException on CompetenceCourseManagementBackingBean ACDM-1821 #resolved

- src/main/java/org/fenixedu/academic/domain/Degree.java
The seperator between the degree type and the degree name is not localized ACDM-1837 #resolve
> Degree.getPresentationNameI18N does not produce a fully localized name ACDM-1837 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/student/ShowStudentStatisticsDispatchAction.java
Previously, the order was undefined since the data comes from a Set.
It is now sorted in descending order, by semester.
> Sort Previous Execution Periods statistics donuts ACDM-1848 #resolve

- src/main/java/org/fenixedu/academic/domain/studentCurriculum/StudentCurricularPlanEnrolmentPreConditions.java
- src/main/java/org/fenixedu/academic/ui/struts/action/student/enrollment/StudentEnrollmentManagementDA.java
- src/main/webapp/student/enrollment/bolonha/showDegreeModulesToEnrol.jsp
also corrected presentation of degree link when it does not exist
> Allowing students to enroll in future execution periods with open enrollment period ACDM-1900 #resolve

- src/main/java/org/fenixedu/academic/domain/studentCurriculum/StudentCurricularPlanEnrolmentInExtraordinarySeasonEvaluationManager.java
- src/main/resources/resources/AcademicAdminOffice_en.properties
- src/main/resources/resources/AcademicAdminOffice_pt.properties
- src/main/webapp/academicAdminOffice/chooseStudentEnrolmentExecutionPeriod.jsp
> Add enrollment in extraordinary season button to student operations in Academic Administrative Office. ACDM-1903 #resolve

- src/main/java/org/fenixedu/academic/ui/struts/action/coordinator/student/curriculum/CurriculumDispatchActionForCoordinator.java
And removed deprecated method in the process
> Prevent NPE when ingression type doesn't exist ACDM-1962 #resolve

- src/main/dml/fenixedu-academic.dml
- src/main/java/org/fenixedu/academic/domain/accounting/AccountingTransaction.java
- src/main/java/org/fenixedu/academic/domain/accounting/Event.java
- src/main/java/org/fenixedu/academic/domain/accounting/IBAN.java
- src/main/java/org/fenixedu/academic/domain/accounting/IBANGroup.java
- src/main/java/org/fenixedu/academic/domain/accounting/IBANPayment.java
- src/main/java/org/fenixedu/academic/domain/accounting/PaymentMethod.java
- added default IBAN payment method connection
- small improvements (indexes, etc)
> Added support for register IBAN payments ACDM-1970 #resolve

- src/main/java/org/fenixedu/academic/report/candidacy/erasmus/LearningAgreementDocument.java
- src/main/java/org/fenixedu/academic/report/phd/notification/PhdCandidacyDeclarationDocument.java
- src/main/java/org/fenixedu/academic/report/phd/notification/PhdNotificationDocument.java
- src/main/java/org/fenixedu/academic/report/phd/registration/PhdSchoolRegistrationDeclarationDocument.java
- src/main/java/org/fenixedu/academic/report/phd/thesis/PhdThesisJuryElementsDocument.java
- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/gradeSubmission/MarkSheetDocument.java
- src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/gradeSubmission/MarkSheetSearchDispatchAction.java
- src/main/java/org/fenixedu/academic/ui/struts/action/internationalRelatOffice/candidacy/erasmus/ErasmusIndividualCandidacyProcessDA.java
- src/main/java/org/fenixedu/academic/ui/struts/action/phd/academicAdminOffice/PhdIndividualProgramProcessDA.java
- src/main/java/org/fenixedu/academic/ui/struts/action/phd/candidacy/academicAdminOffice/PhdProgramCandidacyProcessDA.java
- src/main/java/org/fenixedu/academic/ui/struts/action/phd/thesis/academicAdminOffice/PhdThesisProcessDA.java
- src/main/java/org/fenixedu/academic/ui/struts/action/publico/candidacies/erasmus/ErasmusIndividualCandidacyProcessPublicDA.java
- src/main/java/org/fenixedu/academic/ui/struts/action/teacher/MarkSheetTeacherManagementDispatchAction.java
Converted FenixReports:
Marksheet
Marksheet Rectification
Learning Agreement
PhD Candidacy Declaration
PhD Notification
PhD School Registration Declaration
PhD Thesis Jury Elements
Note: Need to add PapyrusTemplates before deploying to production.
> Generate FenixReports with Papyrus ACDM-1976 #resolve

- src/main/java/org/fenixedu/academic/report/thesis/ApproveJuryDocument.java
- src/main/java/org/fenixedu/academic/report/thesis/StudentThesisIdentificationDocument.java
- src/main/java/org/fenixedu/academic/report/thesis/ThesisDocument.java
- src/main/java/org/fenixedu/academic/ui/struts/action/coordinator/thesis/ManageThesisDA.java
- src/main/java/org/fenixedu/academic/ui/struts/action/scientificCouncil/thesis/ManageSecondCycleThesisDA.java
- src/main/java/org/fenixedu/academic/ui/struts/action/student/thesis/ThesisSubmissionDA.java
* Need to run PapyrusTemplate creator script for it to generate report with Papyrus
> ACDM-1978 #resolve Generate jury approval document and student identification document with Papyrus 
