FenixEdu/fenixedu-academic

src/main/java/org/fenixedu/academic/bootstrap/FenixBootstrapper.java
The 3 letter country code is now verified correctly and produces the desired BootstrapError f an incorrect code is sent. Be it an incorrect one or a two letter country code.
Fixes: https://jira.fenixedu.org/browse/ACADEMIC-333
=> Forces the use of 3 letter country code

src/main/java/org/fenixedu/academic/api/beans/publico/FenixSpace.java, src/main/java/org/fenixedu/academic/domain/space/SpaceUtils.java, src/main/java/org/fenixedu/academic/dto/InfoLesson.java, src/main/java/org/fenixedu/academic/dto/spaceManager/FindSpacesBean.java, src/main/java/org/fenixedu/academic/ui/struts/action/publico/RoomSiteViewerDispatchAction.java, src/main/java/org/fenixedu/academic/ui/struts/action/publico/spaces/FindSpacesDA.java, src/main/resources/resources/ApplicationResources_en.properties, src/main/resources/resources/ApplicationResources_pt.properties, src/main/webapp/publico/spaces/findSpaces.jsp, src/main/webapp/publico/spaces/viewSelectedSpace.jsp, src/main/webapp/publico/viewRoom_bd.jsp
The interface is now re-enabled and adapted to the new fenixedu-spaces.
The layoyt was fixed as the elements, instead of being displayed inline, were stacked.
In the resulting page we now check if the blueprint exists before printing it.
Also in the resulting page, the occupants name are displayed, with the link to their webpages if these are available
=> Fixed search space by person

src/main/java/org/fenixedu/academic/domain/Teacher.java
getTeacherAuthorization(AcademicInterval): Check for an equal interval instead a overlapped one.
=> getTeacherAuthorization: Check for an equal interval instead a overlapped one. ACDM-669 #resolve

src/main/webapp/academicAdministration/bolonha/curricularPlans/curricularPlansManagement.jsp
This improvement is part of the scope of the already closed issue https://jira.fenixedu.org/browse/ACDM-626
=> Made pre-bologna degree codes visible in the curricular plan management interface

src/main/java/org/fenixedu/academic/domain/serviceRequests/documentRequests/DegreeFinalizationCertificateRequest.java, src/main/java/org/fenixedu/academic/domain/serviceRequests/documentRequests/DiplomaRequest.java, src/main/java/org/fenixedu/academic/domain/serviceRequests/documentRequests/DiplomaSupplementRequest.java, src/main/java/org/fenixedu/academic/domain/serviceRequests/documentRequests/RegistryDiplomaRequest.java, src/main/java/org/fenixedu/academic/domain/student/Registration.java, src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/Diploma.java, src/main/java/org/fenixedu/academic/report/academicAdministrativeOffice/DiplomaSupplement.java, src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/serviceRequests/RectorateDocumentSubmissionDispatchAction.java, src/main/webapp/WEB-INF/fenixedu-academic/schemas/serviceRequests-schemas.xml, src/main/webapp/academicAdminOffice/rectorateDocumentSubmission/showBatch.jsp, src/main/webapp/rectorate/showBatch.jsp
Program conclusion document requests enforce requested cycle for legacy
reasons.
Requested cycle can be null when the conclusion refers to a curriculum
group which is not cycle aware.
Issue: ACDM-690
=> ACDM-690 #comment Requested cycle can be null in conclusion document requests

src/main/java/org/fenixedu/academic/domain/student/Registration.java
The following issue changed the way degree description is given by
registration.
Always return the degree description even if the cycle type is null.
Issue: ACDM-690
=> ACDM-690 #comment Return degree description when cycle type is null

src/main/java/org/fenixedu/academic/domain/degreeStructure/CourseGroup.java
When editing course group information the check for duplicate program
conclusion should ignore the current group program conclusion.
Issue: ACDM-690
=> ACDM-690 #comment Ignore current group when checking for conclusions

src/main/java/org/fenixedu/academic/domain/serviceRequests/documentRequests/DiplomaSupplementRequest.java, src/main/java/org/fenixedu/academic/domain/serviceRequests/documentRequests/RegistryDiplomaRequest.java
This approach is much cleaner since there is no prior association
of program conclusion which would break searching for duplicate requests of the affected types.
Issue: ACDM-820
=> Set program conclusion after duplicate check ACDM-820 #resolve

src/main/java/org/fenixedu/academic/ui/struts/action/resourceAllocationManager/PeriodsDA.java
* This prevents some issues with different bean types when creating
a new period right after editing an existing one
* Issue: ACDM-861
=> Properly invalidate view state in Periods Management Interface

src/main/java/org/fenixedu/academic/service/services/person/SearchPerson.java
* Previously worked based on PERSON role, since the roles were refactored the best approach is to question the users's login validity.
=> Fixed SearchPerson's active parameter. ACDM-875 #resolve

src/main/java/org/fenixedu/academic/domain/accounting/installments/InstallmentForFirstTimeStudents.java, src/main/java/org/fenixedu/academic/domain/accounting/installments/InstallmentWithMonthlyPenalty.java
Do not ignore years when calculating number of months for penalty.
Issue: ACDM-877
This may reopen previously closed debts! If so handle your data the way you see fit at your institution. Either you want to reopen the debt and receive the amount due or you can create excemptions in the same value as the change.
=> Do not ignore years when calculating number of months for penalty. #ACDM-877 resolve

src/main/java/org/fenixedu/academic/ui/struts/action/alumni/AlumniHomeDA.java, src/main/webapp/alumni/index.jsp
The completion mechanism was checking the wrong property, SalaryType,
instead of the correct one, Salary. Thus, the profile was never complete.
=> Fixed issue that blocked alumni profile completion ACDM-889 #resolve

src/main/java/org/fenixedu/academic/domain/util/email/Message.java
When the message body is null the system will skip the message and will
show the number of recipients as 0.
=> Fixed message sending problem when body is null ACDM-781 #resolve

src/main/java/org/fenixedu/academic/service/services/enrollment/shift/EnrollStudentInShifts.java, src/main/java/org/fenixedu/academic/ui/struts/action/teacher/ManageExecutionCourseDA.java
* This also unlocks Resource Allocation Manager enrolments on locked shifts
* Don't throw an exception in the enrolment service, let invokers deal with
failed shifts
* Issue: ACDM-925
=> Properly show error messages when attempting to enrol on full shifts

src/main/java/org/fenixedu/academic/domain/student/Registration.java
* As the generated MDCandidacy has no ingression type, the Registration
constructor must take that into account
* Issue: ACDM-935
=> Handle missing ingression type on affinity cycle enrolment

src/main/java/org/fenixedu/academic/domain/reports/RaidesGraduationReportFile.java
prevents students that changed to a new curricular plan from not appearing in the report
=> Fixed filter that left out some students ACDM-943 #resolve

src/main/java/org/fenixedu/academic/service/services/person/PersonSearcher.java, src/main/java/org/fenixedu/academic/ui/struts/action/academicAdministration/payments/PaymentsManagementDA.java, src/main/resources/resources/AcademicAdminOffice_en.properties, src/main/resources/resources/AcademicAdminOffice_pt.properties, src/main/webapp/academicAdministration/payments/events/searchPersons.jsp
This search, when made too broad, led to a clientside timeout, and to
an huge, useless, computation, on the server.
This fix introduces a limit to the number of returned results and a
warning if there are too much results, so the user can refine its search.
=> Enhance Find Person Dialog ACDM-923 #resolve

src/main/java/org/fenixedu/academic/domain/accounting/installments/InstallmentForFirstTimeStudents.java, src/main/java/org/fenixedu/academic/domain/accounting/installments/InstallmentWithMonthlyPenalty.java, src/main/java/org/fenixedu/academic/dto/accounting/paymentPlan/InstallmentBean.java
When defining payment plans the maximum number of months to apply the penalty is no longer mandatory and the system now allows an unlimited number of penalty months
=> Allowed unlimited number of months to apply installment penalty ACDM-931 #resolve

src/main/java/org/fenixedu/academic/domain/WrittenEvaluation.java, src/main/java/org/fenixedu/academic/dto/student/StudentPortalBean.java
Due to conversions between java.util.Date java.util.Calendar and
org.joda.time.DateTime an extra 13 seconds where being added.
This made the interval computation fail when the end time was close to the
midnight
=>  ACDM-1020 #resolve Fix NPE when enrollment end time was close to midnight

src/main/dml/fenixedu-academic.dml, src/main/java/org/fenixedu/academic/domain/accessControl/CoordinatorGroup.java, src/main/java/org/fenixedu/academic/domain/accessControl/PersistentCoordinatorGroup.java
Add responsible groupArgument to CoordinatorGroup.
From now on it is possible to create a CoordinatorGroup with
responsible. Null is a possible value meaning responsible and
non-responsible coordinators, keeping the original semantics.
Issue: ACDM-1009
=> Add responsible to CoordinatorGroup. ACDM-1009 #resolve

src/main/webapp/accounts/createPerson.jsp
ACDM-642 was being caused by a null nationality, when trying to get `nationality.localizedName.content`. In order to fix this, the results table had to be re-written without renderers.
=> Manage accounts interface problems ACDM-642 #resolve

src/main/java/org/fenixedu/academic/dto/degreeAdministrativeOffice/gradeSubmission/GradesToSubmitExecutionCourseSendMailBean.java
When no curricular plan was specified, the number of students without grade would not be counted, which was causing it to show up as 0.
=> Teachers wrongly warned about missing grades submission ACDM-1060 #resolve

src/main/java/org/fenixedu/academic/domain/ExecutionCourse.java
Evaluation method is removed on evaluation course deletion.
=> Evaluation method is no longer a deletion blocker of an evaluation course. ACDM-1182 #resolve

src/main/java/org/fenixedu/academic/ui/renderers/providers/StudentStatuteTypeProvider.java, src/main/java/org/fenixedu/academic/ui/renderers/providers/choiceType/replacement/multiple/StudentStatuteTypeProvider.java, src/main/java/org/fenixedu/academic/ui/renderers/providers/choiceType/replacement/single/StudentStatuteTypeProvider.java
Following exception occurs when any student statute is chosen:
java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.lang.String
at pt.ist.fenixWebFramework.rendererExtensions.converters.DomainObjectKeyConverter.convert(DomainObjectKeyConverter.java:34)
Issue: ACDM-948
=> StudentListByDegreeDA: unable to search by StudentStatute. ACDM-948 #resolve

src/main/resources/resources/CaseHandlingResources_en.properties, src/main/resources/resources/CaseHandlingResources_pt.properties
Notice that the destination page's title refers to the Candidate instead of the Candidacy (which is inconsistent).
Also, there's a bunch (or most) of English resources for this page that are a copy of the Portuguese version. I added these new strings in Portuguese as well to ensure consistency.
=> Add missing string resources for MoveCandidacy ACDM-1082 #resolve

src/main/resources/resources/StudentResources_en.properties, src/main/resources/resources/StudentResources_pt.properties, src/main/webapp/student/enrollment/evaluations/showWrittenEvaluations.jsp
Also, on each evaluation the assigned room for the student appears in bold, unless the enrollment period is open.
Changed the room label to comply with multiple rooms.
=> Show all evaluation rooms on showWrittenEvaluations ACDM-1155 #resolve

src/main/java/org/fenixedu/academic/domain/Alumni.java, src/main/java/org/fenixedu/academic/domain/AlumniIdentityCheckRequest.java
Approval field of AlumniIdentityCheckRequest is a Boolean (not the primitive type boolean) and it is not initialized during the creation of the object so it can be null when a request is pending.
=> Fix NPE on verifying approval of AlumniIdentityCheckRequest ACDM-1209 #resolve

src/main/java/org/fenixedu/academic/task/CreateAdministrativeOfficeFeeEvent.java
Move the transaction code to a separate method when a domain exception was being caught during a transaction.
=> Don't catch domain exceptions during transactions ACDM-1279 #resolve

src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/lists/StudentListByDegreeDA.java, src/main/java/org/fenixedu/academic/ui/struts/action/administrativeOffice/lists/StudentsListByCurricularCourseDA.java
This filename is used to create the response header as such it is now in double quotes as commas can generate issues.
Fixed the issue with listings by curricular course as well.
=> Add quotes to response header in export to excel ACDM-1365 #resolve

src/main/webapp/phd/academicAdminOffice/serviceRequests/viewPhdAcademicServiceRequestsHistoric.jsp
It is not possible to download the generated document of a delivered document request in PhD contexts.
A download/print link should be added to each delivered document request on requests' history interface.
Extra refactoring:
Changed hard-coded schema to existing one ("AcademicServiceRequest.view-for-given-registration")
=> Download/print delivered IDocumentRequest ACDM-1372 #resolve

src/main/java/org/fenixedu/academic/domain/student/Registration.java, src/main/java/org/fenixedu/academic/ui/struts/action/student/enrollment/ShiftStudentEnrollmentManagerDispatchAction.java, src/main/java/org/fenixedu/academic/ui/struts/action/student/enrollment/ShiftStudentEnrollmentManagerLookupDispatchAction.java, src/main/resources/resources/StudentResources_en.properties, src/main/resources/resources/StudentResources_pt.properties
- Before shift reservations students have to choose which reservation they want.
- In extra-curricular page it is not possible to add a course if the chosen registration is not active.
- In shift reservations students can see the schedule for all registrations combined but if they want to reserve shifts they need to select the registration that contains it.
=> Shift reservation now attends to all registrations ACDM-1359 #resolve

src/main/webapp/candidacy/erasmus/viewErasmusVacancies.jsp
- Missing .content in viewErasmusVacancies.jsp to show program's name properly.
=> Name shown as json object in view mobility agreements functionality ACDM-1292 #resolve

src/main/java/org/fenixedu/academic/ui/struts/action/manager/ManageAssociatedObjects.java, src/main/resources/resources/ManagerResources_en.properties, src/main/resources/resources/ManagerResources_pt.properties, src/main/webapp/manager/createScientificArea.jsp
**Action**: press either "submit" or "cancel" buttons with empty fields
**"Cancel" Case**
- Cancel button action was not defined so it defaulted to "submit" behavior.
- Fixed by using fr:destination tag to define cancel action.
**"Submit" Case**
- createScientificArea method tried to get a DepartmentUnit from a null (empty field) when calling bean.getDepartment().getDepartmentUnit().
- Fixed by making the department mandatory
- Also, with only empty name field a DomainException was thrown and not handled.
- Fixed with try/catch to handle domain exception and added error message.
**Extra Refactoring**
- Removed forward mapping "show" since it had no references in the code
=> Manage Associated Objects - Create Scientific Area throws NPE ACDM-1276 #resolve

src/main/webapp/scientificCouncil/competenceCourses/competenceCoursesManagement.jsp, src/main/webapp/scientificCouncil/competenceCourses/showCompetenceCourse.jsp
Move links to competence course page.
This will improve performence when rendering the competenceCoursesManagement interface that lists all courses.
=> Improve performance of competenceCoursesManagement interface ACDM-1418 #resolve

src/main/dml/fenixedu-academic.dml, src/main/java/org/fenixedu/academic/domain/accounting/Event.java, src/main/java/org/fenixedu/academic/domain/accounting/events/AnnualEvent.java, src/main/java/org/fenixedu/academic/domain/accounting/events/gratuity/GratuityEvent.java, src/main/java/org/fenixedu/academic/domain/accounting/installments/InstallmentForFirstTimeStudents.java
Register event start date and use it to calculate when first time student instalments are due.
[Update Scripts](https://gist.github.com/Luis-Cruz/8dd91562b514f80524e10ec1d88ed04d)
The SQL script must be run during the deployment process.
The Custom Task must be run after the application boots.
=> Register event start date ACDM-1498 #resolve

src/main/java/org/fenixedu/academic/domain/accounting/calculator/Debt.java, src/main/java/org/fenixedu/academic/domain/accounting/events/gratuity/GratuityEvent.java, src/main/java/org/fenixedu/academic/dto/accounting/PaymentsManagementDTO.java, src/main/java/org/fenixedu/academic/ui/spring/controller/AccountingController.java, src/main/java/org/fenixedu/academic/ui/spring/controller/AccountingEventsPaymentManagerController.java, src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-debt-details.jsp, src/main/webapp/WEB-INF/fenixedu-academic/accounting/event-details.jsp, src/main/webapp/WEB-INF/fenixedu-academic/accounting/events-multiple-payments-confirm.jsp, src/main/webapp/WEB-INF/fenixedu-academic/accounting/events-multiple-payments-prepare.jsp, src/main/webapp/WEB-INF/fenixedu-academic/accounting/events.jsp, src/main/webapp/WEB-INF/resources/ApplicationResources.properties, src/main/webapp/WEB-INF/resources/ApplicationResources_en.properties, src/main/webapp/WEB-INF/resources/ApplicationResources_pt.properties
- Fixed **bug** caused by disabled checkboxes data not being passed to server
- Changed GratuityEvent description getters to be more consistent
1. Changes to GratuityEvent getDescriptionForEntryType to be consistent with getDescription
~~2. Removal of "select all checkboxes" feature in multiple payments interface~~
~~3. Should a TreeMap be used instead of HashMap to make event ordering consistent every time on the multiple payments interface?~~
=> Improve multiple payments interface logic ACDM-1493

src/main/dml/fenixedu-academic.dml, src/main/java/org/fenixedu/academic/domain/accounting/events/insurance/InsuranceEvent.java, src/main/java/org/fenixedu/academic/domain/accounting/postingRules/InsurancePR.java, src/main/resources/resources/ApplicationResources_en.properties, src/main/resources/resources/ApplicationResources_pt.properties, src/main/webapp/WEB-INF/fenixedu-academic/schemas/prices-schemas.xml, src/main/webapp/manager/payments/postingRules/management/showInsurancePostingRules.jsp
```
alter table `POSTING_RULE` add `NUMBER_OF_DAYS_TO_CALCULATE_DUE_DATE` int(11) DEFAULT NULL;
alter table `EVENT` add `DUE_DATE` datetime NULL default NULL;
update EVENT set DUE_DATE = DATE_ADD(WHEN_OCCURED, INTERVAL 60 DAY) where oid2cname(OID) = 'org.fenixedu.academic.domain.accounting.events.insurance.InsuranceEvent';
update POSTING_RULE set NUMBER_OF_DAYS_TO_CALCULATE_DUE_DATE = 60 where oid2cname(OID) = 'org.fenixedu.academic.domain.accounting.postingRules.InsurancePR';
```
=> InsurancePR: Add number of days to due date ACDM-1506 #resolve

pom.xml
Added explicit jackson.annotation dependency since we were using twilio's transitive dependency (which broke things in testing when it mismatched with jackson.databind-core).
=> Update dependencies using Versions Maven Plugin ACDM-1527 #resolve

pom.xml, src/main/java/org/fenixedu/academic/domain/person/HumanName.java
This upgrade is important mainly for the security fixes (e.g. **hash flooding protection**).
There are some method deprecations in the io.Files but no breaking removals yet.
Only breaking changes was CharMatcher that instead of providing public static constants, now provides public static factory methods.
**Release Links**
- https://github.com/google/guava/wiki/Release22
- https://github.com/google/guava/wiki/Release23
- https://github.com/google/guava/releases (23.1 to 27.0)
=> Upgrade to Guava 27.0

pom.xml
Twilio SDK provided a jackson-core dependency which was inconsistent with our recent jackson dependencies update.
`+- com.twilio.sdk:twilio:jar:7.29.0:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.8.11:compile
[INFO] |  |  \- javax.xml.bind:jaxb-api:jar:2.2:compile
[INFO] |  |     \- javax.xml.stream:stax-api:jar:1.0-2:compile`
=> Add explicit jackson-core dependency to override twilio transitive version ACDM-1533 #resolve

src/main/java/org/fenixedu/academic/ui/faces/bean/bolonhaManager/curricularRules/CurricularRulesManagementBackingBean.java
Now it is possible to add the following rule: To enrol in curricular course X the student must have been enroled before in course X.
=> Change curricular rule for enrolment precedences ACDM-1248 #resolve

src/main/webapp/javaScript/sviz/sviz.css
Previously, without this CSS property, the donuts were visually cut in the UI. Now they are shown properly.
=> Add `box-sizing: content-box` to donuts in Student Statistics page ACDM-1847 #resolve
